COUNTRIES = {
    u"Afghanistan": u"Kabul",
    u"Åland Islands": u"Mariehamn",
    u"Albania": u"Tirana",
    u"Algeria": u"Algiers",
    u"American Samoa": u"Pago Pago",
    u"Andorra": u"Andorra la Vella",
    u"Angola": u"Luanda",
    u"Anguilla": u"The Valley",
    u"Antigua and Barbuda": u"Saint John's",
    u"Argentina": u"Buenos Aires",
    u"Armenia": u"Yerevan",
    u"Aruba": u"Oranjestad",
    u"Australia": u"Canberra",
    u"Austria": u"Vienna",
    u"Azerbaijan": u"Baku",
    u"The Bahamas": u"Nassau",
    u"Bahrain": u"Manama",
    u"Bangladesh": u"Dhaka",
    u"Barbados": u"Bridgetown",
    u"Belarus": u"Minsk",
    u"Belgium": u"Brussels",
    u"Belize": u"Belmopan",
    u"Benin": u"Porto-Novo",
    u"Bermuda": u"Hamilton",
    u"Bhutan": u"Thimphu",
    u"Bolivia": u"Sucre",
    u"Bonaire": u"Kralendijk",
    u"Bosnia and Herzegovina": u"Sarajevo",
    u"Botswana": u"Gaborone",
    u"Bouvet Island": u"",
    u"Brazil": u"Brasília",
    u"British Indian Ocean Territory": u"Diego Garcia",
    u"United States Minor Outlying Islands": u"",
    u"British Virgin Islands": u"Road Town",
    u"Brunei": u"Bandar Seri Begawan",
    u"Bulgaria": u"Sofia",
    u"Burkina Faso": u"Ouagadougou",
    u"Burundi": u"Bujumbura",
    u"Cambodia": u"Phnom Penh",
    u"Cameroon": u"Yaoundé",
    u"Canada": u"Ottawa",
    u"Cape Verde": u"Praia",
    u"Cayman Islands": u"George Town",
    u"Central African Republic": u"Bangui",
    u"Chad": u"N'Djamena",
    u"Chile": u"Santiago",
    u"China": u"Beijing",
    u"Christmas Island": u"Flying Fish Cove",
    u"Cocos (Keeling) Islands": u"West Island",
    u"Colombia": u"Bogotá",
    u"Comoros": u"Moroni",
    u"Republic of the Congo": u"Brazzaville",
    u"Democratic Republic of the Congo": u"Kinshasa",
    u"Cook Islands": u"Avarua",
    u"Costa Rica": u"San José",
    u"Croatia": u"Zagreb",
    u"Cuba": u"Havana",
    u"Curaçao": u"Willemstad",
    u"Cyprus": u"Nicosia",
    u"Czech Republic": u"Prague",
    u"Denmark": u"Copenhagen",
    u"Djibouti": u"Djibouti",
    u"Dominica": u"Roseau",
    u"Dominican Republic": u"Santo Domingo",
    u"Ecuador": u"Quito",
    u"Egypt": u"Cairo",
    u"El Salvador": u"San Salvador",
    u"Equatorial Guinea": u"Malabo",
    u"Eritrea": u"Asmara",
    u"Estonia": u"Tallinn",
    u"Ethiopia": u"Addis Ababa",
    u"Falkland Islands": u"Stanley",
    u"Faroe Islands": u"Tórshavn",
    u"Fiji": u"Suva",
    u"Finland": u"Helsinki",
    u"France": u"Paris",
    u"French Guiana": u"Cayenne",
    u"French Polynesia": u"Papeetē",
    u"French Southern and Antarctic Lands": u"Port-aux-Français",
    u"Gabon": u"Libreville",
    u"The Gambia": u"Banjul",
    u"Georgia": u"Tbilisi",
    u"Germany": u"Berlin",
    u"Ghana": u"Accra",
    u"Gibraltar": u"Gibraltar",
    u"Greece": u"Athens",
    u"Greenland": u"Nuuk",
    u"Grenada": u"St. George's",
    u"Guadeloupe": u"Basse-Terre",
    u"Guam": u"Hagåtña",
    u"Guatemala": u"Guatemala City",
    u"Guernsey": u"St. Peter Port",
    u"Guinea": u"Conakry",
    u"Guinea-Bissau": u"Bissau",
    u"Guyana": u"Georgetown",
    u"Haiti": u"Port-au-Prince",
    u"Heard Island and McDonald Islands": u"",
    u"Honduras": u"Tegucigalpa",
    u"Hong Kong": u"City of Victoria",
    u"Hungary": u"Budapest",
    u"Iceland": u"Reykjavik",
    u"India": u"New Delhi",
    u"Indonesia": u"Jakarta",
    u"Ivory Coast": u"Yamoussoukro",
    u"Iran": u"Tehran",
    u"Iraq": u"Baghdad",
    u"Republic of Ireland": u"Dublin",
    u"Isle of Man": u"Douglas",
    u"Israel": u"Jerusalem",
    u"Italy": u"Rome",
    u"Jamaica": u"Kingston",
    u"Japan": u"Tokyo",
    u"Jersey": u"Saint Helier",
    u"Jordan": u"Amman",
    u"Kazakhstan": u"Astana",
    u"Kenya": u"Nairobi",
    u"Kiribati": u"South Tarawa",
    u"Kuwait": u"Kuwait City",
    u"Kyrgyzstan": u"Bishkek",
    u"Laos": u"Vientiane",
    u"Latvia": u"Riga",
    u"Lebanon": u"Beirut",
    u"Lesotho": u"Maseru",
    u"Liberia": u"Monrovia",
    u"Libya": u"Tripoli",
    u"Liechtenstein": u"Vaduz",
    u"Lithuania": u"Vilnius",
    u"Luxembourg": u"Luxembourg",
    u"Macau": u"",
    u"Republic of Macedonia": u"Skopje",
    u"Madagascar": u"Antananarivo",
    u"Malawi": u"Lilongwe",
    u"Malaysia": u"Kuala Lumpur",
    u"Maldives": u"Malé",
    u"Mali": u"Bamako",
    u"Malta": u"Valletta",
    u"Marshall Islands": u"Majuro",
    u"Martinique": u"Fort-de-France",
    u"Mauritania": u"Nouakchott",
    u"Mauritius": u"Port Louis",
    u"Mayotte": u"Mamoudzou",
    u"Mexico": u"Mexico City",
    u"Federated States of Micronesia": u"Palikir",
    u"Moldova": u"Chișinău",
    u"Monaco": u"Monaco",
    u"Mongolia": u"Ulan Bator",
    u"Montenegro": u"Podgorica",
    u"Montserrat": u"Plymouth",
    u"Morocco": u"Rabat",
    u"Mozambique": u"Maputo",
    u"Myanmar": u"Naypyidaw",
    u"Namibia": u"Windhoek",
    u"Nauru": u"Yaren",
    u"Nepal": u"Kathmandu",
    u"Netherlands": u"Amsterdam",
    u"New Caledonia": u"Nouméa",
    u"New Zealand": u"Wellington",
    u"Nicaragua": u"Managua",
    u"Niger": u"Niamey",
    u"Nigeria": u"Abuja",
    u"Niue": u"Alofi",
    u"Norfolk Island": u"Kingston",
    u"North Korea": u"Pyongyang",
    u"Northern Mariana Islands": u"Saipan",
    u"Norway": u"Oslo",
    u"Oman": u"Muscat",
    u"Pakistan": u"Islamabad",
    u"Palau": u"Ngerulmud",
    u"Palestine": u"Ramallah",
    u"Panama": u"Panama City",
    u"Papua New Guinea": u"Port Moresby",
    u"Paraguay": u"Asunción",
    u"Peru": u"Lima",
    u"Philippines": u"Manila",
    u"Pitcairn Islands": u"Adamstown",
    u"Poland": u"Warsaw",
    u"Portugal": u"Lisbon",
    u"Puerto Rico": u"San Juan",
    u"Qatar": u"Doha",
    u"Republic of Kosovo": u"Pristina",
    u"Réunion": u"Saint-Denis",
    u"Romania": u"Bucharest",
    u"Russia": u"Moscow",
    u"Rwanda": u"Kigali",
    u"Saint Barthélemy": u"Gustavia",
    u"Saint Helena": u"Jamestown",
    u"Saint Kitts and Nevis": u"Basseterre",
    u"Saint Lucia": u"Castries",
    u"Saint Martin": u"Marigot",
    u"Saint Pierre and Miquelon": u"Saint-Pierre",
    u"Saint Vincent and the Grenadines": u"Kingstown",
    u"Samoa": u"Apia",
    u"San Marino": u"City of San Marino",
    u"São Tomé and Príncipe": u"São Tomé",
    u"Saudi Arabia": u"Riyadh",
    u"Senegal": u"Dakar",
    u"Serbia": u"Belgrade",
    u"Seychelles": u"Victoria",
    u"Sierra Leone": u"Freetown",
    u"Singapore": u"Singapore",
    u"Sint Maarten": u"Philipsburg",
    u"Slovakia": u"Bratislava",
    u"Slovenia": u"Ljubljana",
    u"Solomon Islands": u"Honiara",
    u"Somalia": u"Mogadishu",
    u"South Africa": u"Pretoria",
    u"South Georgia": u"King Edward Point",
    u"South Korea": u"Seoul",
    u"South Sudan": u"Juba",
    u"Spain": u"Madrid",
    u"Sri Lanka": u"Colombo",
    u"Sudan": u"Khartoum",
    u"Suriname": u"Paramaribo",
    u"Svalbard and Jan Mayen": u"Longyearbyen",
    u"Swaziland": u"Lobamba",
    u"Sweden": u"Stockholm",
    u"Switzerland": u"Bern",
    u"Syria": u"Damascus",
    u"Taiwan": u"Taipei",
    u"Tajikistan": u"Dushanbe",
    u"Tanzania": u"Dodoma",
    u"Thailand": u"Bangkok",
    u"East Timor": u"Dili",
    u"Togo": u"Lomé",
    u"Tokelau": u"Fakaofo",
    u"Tonga": u"Nuku'alofa",
    u"Trinidad and Tobago": u"Port of Spain",
    u"Tunisia": u"Tunis",
    u"Turkey": u"Ankara",
    u"Turkmenistan": u"Ashgabat",
    u"Turks and Caicos Islands": u"Cockburn Town",
    u"Tuvalu": u"Funafuti",
    u"Uganda": u"Kampala",
    u"Ukraine": u"Kiev",
    u"United Arab Emirates": u"Abu Dhabi",
    u"United Kingdom": u"London",
    u"United States": u"Washington D.C.",
    u"Uruguay": u"Montevideo",
    u"Uzbekistan": u"Tashkent",
    u"Vanuatu": u"Port Vila",
    u"Venezuela": u"Caracas",
    u"Vietnam": u"Hanoi",
    u"Wallis and Futuna": u"Mata-Utu",
    u"Western Sahara": u"El Aaiún",
    u"Yemen": u"Sana'a",
    u"Zambia": u"Lusaka",
    u"Zimbabwe": u"Harare",
}
